### ISSUE TITLE
Pomegranate disregards order in Aether dependency APIs

### ISSUE THREAD

**Issue by glts** [cemerick/pomegranate#86]
I’m sorry to report that I believe there is a flaw in
Pomegranate/Aether’s dependency resolution functionality.

In Maven, a fundamental property of dependency trees is that they are
ordered (occurrence order). The most obvious place where dependency
order is significant is in the construction of classpaths.

The data structures returned by Pomegranate from Aether API calls are
inherently unordered (maps and sets), thus losing the order property
– even though the Aether API itself uses ordered collections.

An example: I tried the `add-dependencies` example from the README with
`[ring/ring-core "1.0.0"]`:

```clojure
{[ring/ring-core "1.0.0"]
 #{[org.clojure/clojure "1.2.1"]
   [commons-codec "1.4"]
   [javax.servlet/servlet-api "2.5"]
   [commons-io "1.4"]
   [commons-fileupload "1.2.1"]},
 [org.clojure/clojure "1.2.1"] nil,
 [commons-codec "1.4"] nil,
 [commons-io "1.4"] nil,
 [commons-fileupload "1.2.1"] nil,
 [javax.servlet/servlet-api "2.5"] nil}
```

The map entries appear in the correct order because the map is small,
the set elements appear out of order. `add-dependencies` should rather
return something like the following, or perhaps use third-party ordered
maps or sets. (This is not very pretty …)

```clojure
[[[ring/ring-core "1.0.0"]
  [org.clojure/clojure "1.2.1"]
  [commons-codec "1.4"]
  [commons-io "1.4"]
  [commons-fileupload "1.2.1"]
  [javax.servlet/servlet-api "2.5"]]
 [org.clojure/clojure "1.2.1"]
 [commons-codec "1.4"]
 [commons-io "1.4"]
 [commons-fileupload "1.2.1"]
 [javax.servlet/servlet-api "2.5"]]
```

I stumbled on this when I looked into technomancy/leiningen#2283 very
briefly this afternoon. If this is just a misunderstanding on my part,
my apologies. Thank you.

**Comment by glts** [comment]
I have briefly looked at the code. Obviously the dependency graph data structure cannot easily be changed without considerable impact both internally and to consumers.

A possible approach: record the order of the keys in the map (= dep specs) as metadata on the map, and record the order of dependencies in the sets as metadata on the set. Then the API can remain unchanged, and the doc strings may point to the order information still being available as metadata.

**Comment by glts** [comment]
I tried the metadata approach. It seems to work, all tests pass.

```diff
diff --git a/src/main/clojure/cemerick/pomegranate/aether.clj b/src/main/clojure/cemerick/pomegranate/aether.clj
index 62c2967..7ad3bd5 100644
--- a/src/main/clojure/cemerick/pomegranate/aether.clj
+++ b/src/main/clojure/cemerick/pomegranate/aether.clj
@@ -457,16 +457,31 @@ kwarg to the repository kwarg.
                              (optional-artifact [:extension "pom"] pom-file)
                              (optional-artifact [] jar-file)))))))
 
+(defn- recording-order-in-meta
+  [coll xs]
+  (and coll
+       (vary-meta coll update-in [:ordered-keys] (comp vec distinct concat) xs)))
+
+(defn- update-graph-with-dep
+  [g ^DependencyNode node dep]
+  (let [spec (dep-spec dep)
+        child-deps (->> (.getChildren node)
+                        (map #(.getDependency %))
+                        (map dep-spec))]
+    (-> g
+        (update-in [spec]
+                   (fn [coll more-deps]
+                     (recording-order-in-meta
+                       (clojure.set/union coll (set more-deps))
+                       more-deps))
+                   child-deps)
+        (recording-order-in-meta [spec]))))
+
 (defn- dependency-graph
   ([node]
     (reduce (fn [g ^DependencyNode n]
               (if-let [dep (.getDependency n)]
-                (update-in g [(dep-spec dep)]
-                           clojure.set/union
-                           (->> (.getChildren n)
-                             (map #(.getDependency %))
-                             (map dep-spec)
-                             set))
+                (update-graph-with-dep g n dep)
                 g))
             {}
             (tree-seq (constantly true)
@@ -820,8 +835,9 @@ kwarg to the repository kwarg.
 (defn dependency-files
   "Given a dependency graph obtained from `resolve-dependencies`, returns a seq of
    files from the dependencies' metadata."
-  [graph]
-  (->> graph keys (map (comp :file meta)) (remove nil?)))
+  [graph & {:keys [preserve-order?]}]
+  (let [selector (if preserve-order? (comp :ordered-keys meta) keys)]
+    (->> graph selector (map (comp :file meta)) (remove nil?))))
 
 (defn- exclusion= [spec1 spec2]
   (let [[dep & opts] (normalize-exclusion-spec spec1)
@@ -871,11 +887,12 @@ kwarg to the repository kwarg.
   "Returns a dependency hierarchy based on the provided dependency graph
    (as returned by `resolve-dependencies`) and the coordinates that should
    be the root(s) of the hierarchy.  Siblings are sorted alphabetically."
-  [root-coordinates dep-graph]
+  [root-coordinates dep-graph & {:keys [preserve-order?] :as opts}]
   (let [root-specs (map (comp dep-spec dependency) root-coordinates)
+        selector (if preserve-order? (comp :ordered-keys meta) keys)
         hierarchy (for [root (filter
                               #(some (fn [root] (within? % root)) root-specs)
-                              (keys dep-graph))]
-                    [root (dependency-hierarchy (dep-graph root) dep-graph)])]
+                              (selector dep-graph))]
+                    [root (apply dependency-hierarchy (dep-graph root) dep-graph (apply concat opts))])]
     (when (seq hierarchy)
       (into (sorted-map-by #(apply compare (map coordinate-string %&))) hierarchy))))
```

I think a change like this would enable downstream projects like
Leiningen to use the order information as needed.

I did not go any further (tests, docstrings) and am curious to hear if
you find this approach acceptable or if you find it terrible … the idea
is that Pomegranate’s position is ‘we represent Aether’s data in
unordered, set-like data structures; but if your application is
sensitive to order, then order information is still available in
metadata’ …

**Comment by hyPiRion** [comment]
If I understand the issue correctly, consumers depend on the map and set-like functionality from Aether, and right now cannot rely on the ordering, right? It could be an option to use [org.flatland/ordered](https://github.com/amalloy/ordered) to let the maps and sets be ordered, but I'm not sure if that would be transparent for downstream consumers (the ordered maps/sets print differently, for example).

The problem is, I don't think it would be transparent for consumers, and it would add an additional dependency that has to be properly packaged for downstream tools like e.g. Leiningen.

**Comment by cemerick** [comment]
I understand the motivation given unfortunate circumstances w.r.t. resource duplication / naming collision in dependency artifacts. However, I'm not keen on enabling those kinds of traps, especially since you can trivially construct a set of dependencies that have no "safe" ordering, depending on the set of conflicting resources they each provide and you are looking to resolve at build- or run-time.

(I am curious as to what _actual_ problem is prompting this; the original report on technomancy/leiningen#2298 provides an example involving Clojure libraries, which should generally be culturally resistant to the kinds of resource collisions that make ordered dependency sets desirable otherwise.)

As for the metadata workaround: the problem with this is that code absolutely exists that manipulates pomegranate dependency info directly, which will always leave this metadata out of sync with its associated collection. If ordering is an essential property of these structures, then it needs to actually be so, instead of being managed separately.

I'm not against using flatland/ordered.

**Comment by glts** [comment]
Thank you for thinking about this. I’m fine with a ‘no’ of course. I
want two share just two thoughts and then leave it be.

In the traditional enterprisey Java application world, I have
encountered those mythological classpath ordering issues every once in a
while, some directly experienced, some plausible hearsay. In one large,
grown Maven-built application I’m currently only too familiar with, no
one would dare giving up classpath order out of fear: anything could
happen. With this background, the argument in favour of retaining order
here is probably, ‘do it like Maven, just in case’. If such
circumstances are ruled out by a different culture in Clojure, as you
say, then we don’t need it.

The other thought is, are there cases where downstream absolutely needs
the order information? Apparently Clojure core people have been thinking
about this for tools.deps. Alex Miller discusses this topic in
https://youtu.be/sStlTye-Kjk. For tools.deps they have decided that
classpath order is not relevant – but they provide an ‘override’
mechanism for those cases where order matters. So that might be
something a Pomegranate consumer could consider introducing, without
needing any change in Pomegranate.

**Comment by cemerick** [comment]
I have Alex's talk queued, but haven't gotten there yet. Thanks for the prod.

I've had my share of experience with traditional Java environments, and I agree, in that venue, "this is how it is, don't touch it" is definitely a sane default. There are two things influencing me at the moment:

1. I have personally hit situations where there's a requirement to get a resource named `A` from dependency `X`, and a resource `B` from dependency `Y`, but `X` _also_ includes a `B` and `Y` _also_ includes an `A`. Given that, there is no classpath ordering that will make a simple resource URL lookup for both `A` and `B` find the things you want, so you end up having to fall back to classpath scanning and various incredibly-fragile methods for identifying which `A`s and `B`s you actually want. <br/><br/>This is all to say that, even stable dependency ordering is an insufficient solution to these kinds of "problems".
2. Insofar as dependency-order sensitivity is a wart/irritant/trap/etc, I appreciate that pomegranate makes no dependency ordering guarantees. It's a crude (or cruel?) methodology, but transiently-failing builds/tests are a brake on allowing libraries and applications to harbor the kinds of unfortunate choices that make order sensitivity necessary.

FWIW, I remain curious about the actual original motivating case. Maybe @rauhs can chime in.

**Comment by rauhs** [comment]
Sorry for being MIA.

So the original motivation for my leiningen ticket was: I wanted to have a custom/forked `core.cljs` and `core.cljc` of clojurescript without actually doing a full fork. For this, I created a jar that *only* contains those two files in the right path so clojure would find it. It first worked putting it in front but after a version bump I noticed it's now completely different order. Hence the ticket.

I know this isn't the greatest of ideas... But it seemed like a reasonable idea at the time. Now, I'd probably lean towards full (local) fork.

I do wonder how often the random ordering is actually the root cause for an issue but is never figured out by the user. IMO, if the order is kept random as it is right now, then there should be a tool that warns if a resource path is in multiple jars.

FWIW, I also think that the new `tools.deps` using a map and giving random ordering is a bad idea.

**Comment by cemerick** [comment]
You're right that your "light" fork approach is "clever" :wink:. The recipe for using a fork of any dependency that I'm familiar with is:

1. Exclude the usual groupId/artifactId within your project globally, viz. https://github.com/technomancy/leiningen/blob/26d530be200bfcac5eb93fce73efd3bf64b007ff/sample.project.clj#L79
2. Add your forked artifact as a dependency

This approach is durable in the face of all sorts of project management stuff, including plugins that manipulate profiles/classpaths.

------

There are all sorts of same-named resources in a typical Clojure/Java app's classpath; it's actually an essential part of all JVM apps because of the META-INF service architecture. (This is one reason of many why uberjarring is actually a nontrivial thing for Java apps generally.) So, even the smallest app would produce warnings if run through a tool that scans for same-named resources.

**Comment by cemerick** [comment]
The primary downstream issue  technomancy/leiningen#2298 is closed, so doing the same here.
