### ISSUE TITLE
resolve-dependencies returns exclusions as vector of vectors

### ISSUE THREAD

**Issue by martinklepsch** [cemerick/pomegranate#93]
Not sure if this is a bug or intentional. Via https://github.com/boot-clj/boot/issues/635

```clojure
(require 'cemerick.pomegranate.aether)

(cemerick.pomegranate.aether/resolve-dependencies
 :coordinates  '[[boot/core "2.7.0" :exclusions [org.clojure/clojure boot/pod]]]
 :repositories  [["clojars" {:url "https://repo.clojars.org/"}]
                 ["maven-central" {:url "https://repo1.maven.org/maven2"}]])

;; returns this:
{[boot/core "2.7.0" :exclusions [[org.clojure/clojure] [boot/pod]]] nil}
```

I would expect it to return exclusions in the same way they were given to `resolve-dependencies`, i.e. in this case the expected return value would be:

```clojure
{[boot/core "2.7.0" :exclusions [org.clojure/clojure boot/pod]] nil}
```

Is this a bug or is there purpose to returning exclusions as vector of vectors? Thanks! :)

PS. I also reproduced this with `v1.0.0`.

**Comment by martinklepsch** [comment]
Any chance someone can comment on whether this is a bug or intentional? It seems like it should be easy to fix so I'm happy to do it if desired. :)

**Comment by cemerick** [comment]
It's intentional. After being passed through aether, exclusions end up being "normalized" to look like any other dependency vector (just absent a version string in that case). Note that the symbol-only representation of exclusion groupId/artifactIds is just a convenience, resolved here:

https://github.com/cemerick/pomegranate/blob/c5a5535b7026e3547b13563904f331175efa9eeb/src/main/clojure/cemerick/pomegranate/aether.clj#L237
